
metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 60s
  configs:
    - name: integrations
      scrape_configs:
        - job_name: integrations/nodejs
          static_configs:
            - targets: ['nodejs-app:4001']
      remote_write:
        - url: https://collegespace215.grafana.net/alerting/grafanacloud-collegespace215-prom/NodejsDown/find
